# Data Type Conversion








#astype()---convert one data type to another

In [1]:
import pandas as pd

In [2]:
import warnings 
warnings.filterwarnings('ignore')

In [3]:
df=pd.DataFrame({
    "Age":['23','24','25'],
    "salary":[25000.6,30000.4,50000.8],
    "Employed":[1,0,1]
})

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       3 non-null      object
 1   salary    3 non-null      int64
 2   Employed  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [5]:
#convert age from object to int
df['Age']=df['Age'].astype(int)
df.dtypes

Age         int64
salary      int64
Employed    int64
dtype: object

In [6]:
df['salary']=df['salary'].astype(int)
df.dtypes

Age         int64
salary      int64
Employed    int64
dtype: object

In [7]:
df['Employed']=df['Employed'].astype(bool)
df.dtypes

Age         int64
salary      int64
Employed     bool
dtype: object

In [9]:
# pd.to_numeric
df['Age']=df['Age'].astype(str)
df.dtypes
df['Age']=pd.to_numeric(df["Age"],errors="coerce")
print(df.dtypes)

Age         int64
salary      int64
Employed     bool
dtype: object

In [10]:
df['joinDate']=pd.to_datetime(['2025-09-09','2024-01-01','2023-12-15'])
df.dtypes

Age                  int64
salary               int64
Employed              bool
joinDate    datetime64[ns]
dtype: object

In [11]:
df['experiance']=pd.to_timedelta(["365 days","730 days","1095 days"])
df.dtypes

Age                     int64
salary                  int64
Employed                 bool
joinDate       datetime64[ns]
experiance    timedelta64[ns]
dtype: object

In [12]:
df["department"]=pd.Series(["HR","IT","Finance"]).astype("category")
df.dtypes

Age                     int64
salary                  int64
Employed                 bool
joinDate       datetime64[ns]
experiance    timedelta64[ns]
department           category
dtype: object

# Row label/index

In [16]:
df=pd.DataFrame({
    "Name":['A','B','C'],
    "Marks":[85,90,78]
},index=[101,102,103])
df

    Name  Marks
101    A     85
102    B     90
103    C     78

In [15]:
print(df.index)
print(df.index.tolist())

RangeIndex(start=0, stop=3, step=1)
[0, 1, 2]

In [18]:
print(df.reset_index())  #keeps old index as column
print('-------------------')
print(df.reset_index(drop=True)) #removes old index

   index Name  Marks
0    101    A     85
1    102    B     90
2    103    C     78
-------------------
  Name  Marks
0    A     85
1    B     90
2    C     78

In [19]:
df=pd.DataFrame({
    "roll":[101,102,103],
    "Name":['A','B','C'],
    "Marks":[85,90,78]
})
df

   roll Name  Marks
0   101    A     85
1   102    B     90
2   103    C     78

In [21]:
df2=df.set_index('roll')
df2

     Name  Marks
roll
101     A     85
102     B     90
103     C     78

In [22]:
df2.loc[102]

Name      B
Marks    90
Name: 102, dtype: object

In [23]:
df.iloc[2]

roll     103
Name       C
Marks     78
Name: 2, dtype: object

In [25]:
df=pd.DataFrame({
    "Name":['A','B','C'],
    "Marks":[85,90,78]
},index=[101,102,103])
df

    Name  Marks
101    A     85
102    B     90
103    C     78

In [26]:
df_renamed=df.rename(index={101:201,103:203})
df_renamed

    Name  Marks
201    A     85
102    B     90
203    C     78

# Adding rows and dropping rows

In [27]:
#use loc and iloc
#concat
# to a new  row at the at end of the use iloc or concat

df=pd.DataFrame({
    "Name":['A','B','C'],
    "Marks":[85,90,78]
},index=[101,102,103])
df

    Name  Marks
101    A     85
102    B     90
103    C     78

In [30]:
df.loc[104]=['D',85]
df

    Name  Marks
101    A     85
102    B     90
103    C     78
104    D     85

In [32]:
# concat
new_row=pd.DataFrame({'Name':['E'],'Marks':[95]},index=[105])
df2=pd.concat([df,new_row])
df2

    Name  Marks
101    A     85
102    B     90
103    C     78
104    D     85
105    E     95

In [33]:
df=pd.DataFrame({
    "Name":['A','B','C'],
    "Marks":[85,90,78]
},index=[101,102,103])
df

    Name  Marks
101    A     85
102    B     90
103    C     78

In [34]:
new_row=pd.DataFrame({'Name':['D'],'Marks':[95]},index=[102])
df2=pd.concat([df,new_row])
df2=df2.sort_index().reset_index(drop=True)
df2

  Name  Marks
0    A     85
1    B     90
2    D     95
3    C     78

In [35]:
new_row=pd.DataFrame({'Name':['D'],'Marks':[95]},index=[100])
df2=pd.concat([df,new_row])
df2=df2.sort_index().reset_index(drop=True)
df2

  Name  Marks
0    D     95
1    A     85
2    B     90
3    C     78

In [37]:
# Droping rows
df=pd.DataFrame({
    "Name":['A','B','C','D'],
    "Marks":[85,90,78,90]
},index=[101,102,103,104])
df

    Name  Marks
101    A     85
102    B     90
103    C     78
104    D     90

In [38]:
df1=df.drop(102)
df1

    Name  Marks
101    A     85
103    C     78
104    D     90

In [40]:
df.drop([102,104],inplace=True)
df

    Name  Marks
101    A     85
103    C     78

# Boolean Row Selection by Values

In [41]:
data={
    "Name":['A','B','C','D','E','F'],
    "Age":[25,30,35,40,45,50],
    "City":["New york","Paris","London","Berlin","paris","London"],
    "Salary":[50000,60000,70000,80000,90000,100000]
}
df=pd.DataFrame(data)
df

  Name  Age      City  Salary
0    A   25  New york   50000
1    B   30     Paris   60000
2    C   35    London   70000
3    D   40    Berlin   80000
4    E   45     paris   90000
5    F   50    London  100000

In [42]:
df[df["Age"]==30]

  Name  Age   City  Salary
1    B   30  Paris   60000

In [44]:
df[df["Age"]!=30]

  Name  Age      City  Salary
0    A   25  New york   50000
2    C   35    London   70000
3    D   40    Berlin   80000
4    E   45     paris   90000
5    F   50    London  100000

In [47]:
# AND Condition (&)
df[(df['Age']>30)& (df['City']=='paris')]

  Name  Age   City  Salary
4    E   45  paris   90000

In [48]:
#OR condition(|)
df[(df['Age']<30)|(df['City']=='paris')]

  Name  Age      City  Salary
0    A   25  New york   50000
4    E   45     paris   90000

In [49]:
# isin() condition
df[df["City"].isin(["Paris","Hyderabad"])]

  Name  Age   City  Salary
1    B   30  Paris   60000

In [50]:
#not in --->(~with isin())
df[~df["City"].isin(["Paris","Hyderabad"])]  #give other than  paris and hydrabad

  Name  Age      City  Salary
0    A   25  New york   50000
2    C   35    London   70000
3    D   40    Berlin   80000
4    E   45     paris   90000
5    F   50    London  100000

In [52]:
 #contains
df[df['City'].str.contains("on")]

  Name  Age    City  Salary
2    C   35  London   70000
5    F   50  London  100000

In [53]:
 #contains
df[~df['City'].str.contains("on")]

  Name  Age      City  Salary
0    A   25  New york   50000
1    B   30     Paris   60000
3    D   40    Berlin   80000
4    E   45     paris   90000

In [55]:
#Between contition
df[df["Age"].between(30,45)]

  Name  Age    City  Salary
1    B   30   Paris   60000
2    C   35  London   70000
3    D   40  Berlin   80000
4    E   45   paris   90000

In [56]:
# not Between contition
df[~df["Age"].between(30,45)]

  Name  Age      City  Salary
0    A   25  New york   50000
5    F   50    London  100000

In [57]:
#startswith 
df[df['City'].str.startswith("N")]

  Name  Age      City  Salary
0    A   25  New york   50000

In [58]:
#endswith
df[df['City'].str.endswith("n")]

  Name  Age    City  Salary
2    C   35  London   70000
3    D   40  Berlin   80000
5    F   50  London  100000

In [59]:
#age>30,city=london,salary>=70000
df[(df['Age']>30)& (df['City']=='paris')&(df['Salary']>=70000)]

  Name  Age   City  Salary
4    E   45  paris   90000