# apply()

In [35]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
data={
    'Name':['Arjun','Bob','Cherry','Dhanush'],
    'Department':['HR','IT','Finance','IT'],
    'Salary':[50000,60000,55000,70000],
    'Joining_year':[2019,2020,2018,2021]
}
df=pd.DataFrame(data)
df

      Name Department  Salary  Joining_year
0    Arjun         HR   50000          2019
1      Bob         IT   60000          2020
2   Cherry    Finance   55000          2018
3  Dhanush         IT   70000          2021

In [12]:
df['Upadated_salary']=df['Salary'].apply(lambda x:x+5000)
df

      Name Department  Salary  Joining_year  Upadated_salary
0    Arjun         HR   50000          2019            55000
1      Bob         IT   60000          2020            65000
2   Cherry    Finance   55000          2018            60000
3  Dhanush         IT   70000          2021            75000

In [13]:
def salary_category(Salary):
    if Salary>=60000:
        return 'High'
    else:
        return 'Low'

df['Salary_category']=df['Salary'].apply( salary_category)
df

      Name Department  Salary  Joining_year  Upadated_salary Salary_category
0    Arjun         HR   50000          2019            55000             Low
1      Bob         IT   60000          2020            65000            High
2   Cherry    Finance   55000          2018            60000             Low
3  Dhanush         IT   70000          2021            75000            High

In [14]:
import datetime

current_year=datetime.datetime.now().year
df['Experiance']=df.apply(lambda row :current_year-row['Joining_year'],axis=1)
df

,Name,Department,Salary,Joining_year,Upadated_salary,Salary_category,Experiance
0,Arjun,HR,50000,2019,55000,Low,7
1,Bob,IT,60000,2020,65000,High,6
2,Cherry,Finance,55000,2018,60000,Low,8
3,Dhanush,IT,70000,2021,75000,High,5

In [15]:
df['Name_upper']=df["Name"].apply(str.upper)
df

,Name,Department,Salary,Joining_year,Upadated_salary,Salary_category,Experiance,Name_upper
0,Arjun,HR,50000,2019,55000,Low,7,ARJUN
1,Bob,IT,60000,2020,65000,High,6,BOB
2,Cherry,Finance,55000,2018,60000,Low,8,CHERRY
3,Dhanush,IT,70000,2021,75000,High,5,DHANUSH

In [21]:
df['Dept_len']=df['Department'].str.len()
df

,Name,Department,Salary,Joining_year,Upadated_salary,Salary_category,Experiance,Name_upper,Dept_len
0,Arjun,HR,50000,2019,55000,Low,7,ARJUN,2
1,Bob,IT,60000,2020,65000,High,6,BOB,2
2,Cherry,Finance,55000,2018,60000,Low,8,CHERRY,7
3,Dhanush,IT,70000,2021,75000,High,5,DHANUSH,2

In [23]:
def add_sal(Salary):
    Salary+=5000
    return Salary

df['Salary_add']=df['Salary'].apply( add_sal)
df

,Name,Department,Salary,Joining_year,Upadated_salary,Salary_category,Experiance,Name_upper,Dept_len,Salary_add
0,Arjun,HR,50000,2019,55000,Low,7,ARJUN,2,55000
1,Bob,IT,60000,2020,65000,High,6,BOB,2,65000
2,Cherry,Finance,55000,2018,60000,Low,8,CHERRY,7,60000
3,Dhanush,IT,70000,2021,75000,High,5,DHANUSH,2,75000

In [24]:
data={
    'Name':['Arjun','Bob','Cherry','Dhanush'],
    'Department':['HR','IT','Finance','IT'],
    'Salary':[50000,60000,55000,70000],
    'Joining_year':[2019,2020,2018,2021]
}
df=pd.DataFrame(data)
df

      Name Department  Salary  Joining_year
0    Arjun         HR   50000          2019
1      Bob         IT   60000          2020
2   Cherry    Finance   55000          2018
3  Dhanush         IT   70000          2021

In [27]:
df['Updated_salary']=df['Salary'].map(lambda x:x+5000)
df

      Name Department  Salary  Joining_year  Updated_salary
0    Arjun         HR   50000          2019           55000
1      Bob         IT   60000          2020           65000
2   Cherry    Finance   55000          2018           60000
3  Dhanush         IT   70000          2021           75000

In [29]:
#map department names to codes
dept_map={'HR':'D1','IT':'D2','Finance':'D3'}
df['Dept_code']=df['Department'].map(dept_map)
df

      Name Department  Salary  Joining_year  Updated_salary Dept_code
0    Arjun         HR   50000          2019           55000        D1
1      Bob         IT   60000          2020           65000        D2
2   Cherry    Finance   55000          2018           60000        D3
3  Dhanush         IT   70000          2021           75000        D2

In [31]:
bonus=pd.Series([500,600,700,800],index=[0,1,2,3])
df['Bonus']=df.index.map(bonus)
df

      Name Department  Salary  Joining_year  Updated_salary Dept_code  Bonus
0    Arjun         HR   50000          2019           55000        D1    500
1      Bob         IT   60000          2020           65000        D2    600
2   Cherry    Finance   55000          2018           60000        D3    700
3  Dhanush         IT   70000          2021           75000        D2    800

In [36]:
data={
    'Salary':[50000,60000,55000,70000],
    'Numbers':[2019,2020,2018,2021]
}
df=pd.DataFrame(data)
df

   Salary  Numbers
0   50000     2019
1   60000     2020
2   55000     2018
3   70000     2021

In [38]:
data={
    'Name':['Arjun','Bob','Cherry','Dhanush'],
    'Department':['HR','IT','Finance','IT'],
    'Salary':[50000,60000,55000,70000],
    'Bouns':[5000,6000,5500,6000]
}
df=pd.DataFrame(data)
df

      Name Department  Salary  Bouns
0    Arjun         HR   50000   5000
1      Bob         IT   60000   6000
2   Cherry    Finance   55000   5500
3  Dhanush         IT   70000   6000

In [39]:
def add_numeric(x):
    if isinstance(x,(int,float)):
        return x+1000
    return x
df_add=df.applymap(add_numeric)
df_add

      Name Department  Salary  Bouns
0    Arjun         HR   51000   6000
1      Bob         IT   61000   7000
2   Cherry    Finance   56000   6500
3  Dhanush         IT   71000   7000

In [40]:
def col_upp(x):
    if isinstance(x,str):
        return x.upper()
    return x
df_upp=df.applymap(col_upp)
df_upp

      Name Department  Salary  Bouns
0    ARJUN         HR   50000   5000
1      BOB         IT   60000   6000
2   CHERRY    FINANCE   55000   5500
3  DHANUSH         IT   70000   6000

In [47]:
df_upper=df.applymap(lambda x:x.upper() if isinstance(x,str) else x)
df_upper

      Name Department  Salary  Bouns
0    ARJUN         HR   50000   5000
1      BOB         IT   60000   6000
2   CHERRY    FINANCE   55000   5500
3  DHANUSH         IT   70000   6000

In [49]:
def numeric(x):
    if isinstance(x,(int,float)):
        if x>60000:
            return 'High'
    return x
df3=df.applymap(numeric)
df3

      Name Department Salary  Bouns
0    Arjun         HR  50000   5000
1      Bob         IT  60000   6000
2   Cherry    Finance  55000   5500
3  Dhanush         IT   High   6000

# Rolling() and Expanding()

In [50]:
sales=pd.Series([10,20,30,40,50])
sales

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [57]:
print("Rolling:\n",sales.rolling(3).mean())
print('----------------------------')
print("Expanding:\n",sales.expanding().mean())

Rolling:
 0     NaN
1     NaN
2    20.0
3    30.0
4    40.0
dtype: float64
----------------------------
Expanding:
 0    10.0
1    15.0
2    20.0
3    25.0
4    30.0
dtype: float64

# json

In [58]:
import json

In [59]:
employee=[
    {'empID':1,"Name":"jhon","Department":"HR","Salary":50000},
    {'empID':2,"Name":"Ram","Department":"Finance","Salary":50000},
    {'empID':1,"Name":"jhon","Department":"IT","Salary":50000},
]

In [61]:
#save this data to json 
with open("employees.json","w") as f:
    json.dump(employee,f,indent=4)

In [62]:
with open("employees.json","r") as f:
    loaded_data=json.load(f)

In [63]:
loaded_data

[{'empID': 1, 'Name': 'jhon', 'Department': 'HR', 'Salary': 50000},
 {'empID': 2, 'Name': 'Ram', 'Department': 'Finance', 'Salary': 50000},
 {'empID': 1, 'Name': 'jhon', 'Department': 'IT', 'Salary': 50000}]

In [64]:
df=pd.read_json("employees.json")
df

   empID  Name Department  Salary
0      1  jhon         HR   50000
1      2   Ram    Finance   50000
2      1  jhon         IT   50000

In [65]:
#convert dataframe to json
df.to_json("emp_output.json",orient='records',indent=4)

In [68]:
json_string='{"empID": 4, "Name": "Ravan", "Department": "Finance", "Salary": 55000}'
print(type(json_string))
parsed=json.loads(json_string)
print(parsed)
print(type(parsed))

<class 'str'>
{'empID': 4, 'Name': 'Ravan', 'Department': 'Finance', 'Salary': 55000}
<class 'dict'>