In [1]:
import pandas as pd

In [2]:
import warnings 
warnings.filterwarnings('ignore')

In [3]:
data={
    'maths':[90,80,70],
    'science':[85,95,75],
    'english':[88,76,92]
}
df=pd.DataFrame(data)
df

   maths  science  english
0     90       85       88
1     80       95       76
2     70       75       92

In [4]:
print(df.sum()) #column wise
print('--------')
print(df.sum(axis=1)) #row wise

maths      240
science    255
english    256
dtype: int64
--------
0    263
1    251
2    237
dtype: int64

In [5]:
#mean--->df.mean()
print(df.mean())

maths      80.000000
science    85.000000
english    85.333333
dtype: float64

In [6]:
#median
print(df.median())

maths      80.0
science    85.0
english    88.0
dtype: float64

In [7]:
print(df.min())
print(df.max())

maths      70
science    75
english    76
dtype: int64
maths      90
science    95
english    92
dtype: int64

In [8]:
#variance
print(df.var())

maths      100.000000
science    100.000000
english     69.333333
dtype: float64

In [9]:
print(df.std())

maths      10.000000
science    10.000000
english     8.326664
dtype: float64

In [10]:
# cumulative sum
print(df.cumsum())

   maths  science  english
0     90       85       88
1    170      180      164
2    240      255      256

In [11]:
#cumulative product
print(df.cumprod())

    maths  science  english
0      90       85       88
1    7200     8075     6688
2  504000   605625   615296

In [12]:
#Absolute value--->Truns negative values into positive values
print(df.abs())

   maths  science  english
0     90       85       88
1     80       95       76
2     70       75       92

In [13]:
#power 
print(df.pow(2))

   maths  science  english
0   8100     7225     7744
1   6400     9025     5776
2   4900     5625     8464

In [15]:
#round()
print(df.round(1))

   maths  science  english
0     90       85       88
1     80       95       76
2     70       75       92

In [16]:
#count()--->Returns the no.of non-NA values in each column
print(df.count())

maths      3
science    3
english    3
dtype: int64

In [17]:
#product
print(df.prod())

maths      504000
science    605625
english    615296
dtype: int64

In [18]:
#mode -->Returns the most frequent value in each column
print(df.mode())

   maths  science  english
0     70       75       76
1     80       85       88
2     90       95       92

In [19]:
#correlation 
#values range---> -1 to +1
print(df.corr())

            maths   science   english
maths    1.000000  0.500000 -0.240192
science  0.500000  1.000000 -0.960769
english -0.240192 -0.960769  1.000000

In [20]:
#covariance 
print(df.cov())

         maths  science    english
maths    100.0     50.0 -20.000000
science   50.0    100.0 -80.000000
english  -20.0    -80.0  69.333333

# column labels/index

In [21]:
df=pd.DataFrame({
    'Name':['a','b','c'],
    'Age':[23,25,21],
    'City':['Delhi','Mumbai','Chennai']
})
df

  Name  Age     City
0    a   23    Delhi
1    b   25   Mumbai
2    c   21  Chennai

In [22]:
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [23]:
print(df.columns[0])

Name

In [24]:
print(list(df.columns))

['Name', 'Age', 'City']

In [25]:
print(df.keys())

Index(['Name', 'Age', 'City'], dtype='object')

In [26]:
df["Name"]

0    a
1    b
2    c
Name: Name, dtype: object

In [27]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [28]:
print(list(df.index))

[0, 1, 2]

In [29]:
print(df.index[0])

0

In [43]:
df=pd.DataFrame({
    'Name':['a','b','c'],
    'Age':[23,25,21],
    'City':['Delhi','Mumbai','Chennai']
})
df

  Name  Age     City
0    a   23    Delhi
1    b   25   Mumbai
2    c   21  Chennai

In [44]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [45]:
## Rename column label
df1=df.rename(columns={'Name':'FullName', 'City':'Location'})
df1

  FullName  Age Location
0        a   23    Delhi
1        b   25   Mumbai
2        c   21  Chennai

In [46]:
df2=df.copy()
df2.columns=['FullName','Years','Location']
df2

  FullName  Years Location
0        a     23    Delhi
1        b     25   Mumbai
2        c     21  Chennai

In [47]:
df2.columns=[i.upper() for i in df2.columns]
df2

  FULLNAME  YEARS LOCATION
0        a     23    Delhi
1        b     25   Mumbai
2        c     21  Chennai

In [48]:
df3=df2.add_prefix('emp_')
df3

  emp_FULLNAME  emp_YEARS emp_LOCATION
0            a         23        Delhi
1            b         25       Mumbai
2            c         21      Chennai

In [49]:
df4=df.add_suffix("_data")
df4

  Name_data  Age_data City_data
0         a        23     Delhi
1         b        25    Mumbai
2         c        21   Chennai

In [50]:
df5=df.set_axis(['full name ','years','location'],axis=1)
df5

  full name   years location
0          a     23    Delhi
1          b     25   Mumbai
2          c     21  Chennai

In [51]:
df5.columns=df5.columns.str.upper()
df5

  FULL NAME   YEARS LOCATION
0          a     23    Delhi
1          b     25   Mumbai
2          c     21  Chennai

# Selecting and swapping columns

In [52]:
df=pd.DataFrame({
    'Name':['a','b','c'],
    'Age':[23,25,21],
    'City':['Delhi','Mumbai','Chennai']
})
df

  Name  Age     City
0    a   23    Delhi
1    b   25   Mumbai
2    c   21  Chennai

In [55]:
print(df["Name"])
print('----------------')
print(df[['Name','City']])
print('------------------')
print(df.iloc[:,0]) #first column
print('------------------')
print(df.iloc[:,[0,2]]) #first and third column
print('------------------')
print(df.iloc[:,0:2])  # first two columns

0    a
1    b
2    c
Name: Name, dtype: object
----------------
  Name     City
0    a    Delhi
1    b   Mumbai
2    c  Chennai
------------------
0    a
1    b
2    c
Name: Name, dtype: object
------------------
  Name     City
0    a    Delhi
1    b   Mumbai
2    c  Chennai
------------------
  Name  Age
0    a   23
1    b   25
2    c   21

In [61]:
#swapping
#manual order
df1=df[['Name','City','Age']]
print(df1)
print('---------------')
#swap two columns(2nd method)
cols=list(df.columns)
cols[1],cols[2]=cols[2],cols[1]
df2=df[cols]
print(df2)
print('---------------')

#3rd method---reindex
df3=df.reindex(columns=['City','Name','Age'])
print(df3)
print('---------------')

#4th method
df4=df.iloc[:,[2,0,1]]
print(df4)

  Name     City  Age
0    a    Delhi   23
1    b   Mumbai   25
2    c  Chennai   21
---------------
  Name     City  Age
0    a    Delhi   23
1    b   Mumbai   25
2    c  Chennai   21
---------------
      City Name  Age
0    Delhi    a   23
1   Mumbai    b   25
2  Chennai    c   21
---------------
      City Name  Age
0    Delhi    a   23
1   Mumbai    b   25
2  Chennai    c   21

# adding new column and drop exisiting column

In [63]:
df=pd.DataFrame({
    'Name':['a','b','c'],
    'Age':[23,25,21],
    'City':['Delhi','Mumbai','Chennai']
})
df

  Name  Age     City
0    a   23    Delhi
1    b   25   Mumbai
2    c   21  Chennai

In [64]:
#add new column
df['country']='India'
df

  Name  Age     City country
0    a   23    Delhi   India
1    b   25   Mumbai   India
2    c   21  Chennai   India

In [66]:
df['marks']=[85,90,94]
df

  Name  Age     City country  marks
0    a   23    Delhi   India     85
1    b   25   Mumbai   India     90
2    c   21  Chennai   India     94

In [69]:
df["Age_after_5years"]=df["Age"]+5
df

  Name  Age     City country  marks  Age_after_5years
0    a   23    Delhi   India     85                28
1    b   25   Mumbai   India     90                30
2    c   21  Chennai   India     94                26

In [73]:
df=df.assign(Status=['pass','pass','pass'])
df

  Name  Age     City country  marks  Age_after_5years Status
0    a   23    Delhi   India     85                28   pass
1    b   25   Mumbai   India     90                30   pass
2    c   21  Chennai   India     94                26   pass

In [75]:
df=df.drop("marks",axis=1)
df

  Name  Age     City country  Age_after_5years Status
0    a   23    Delhi   India                28   pass
1    b   25   Mumbai   India                30   pass
2    c   21  Chennai   India                26   pass

In [77]:
df2=df.drop(['country','Status'],axis=1)
df2

  Name  Age     City  Age_after_5years
0    a   23    Delhi                28
1    b   25   Mumbai                30
2    c   21  Chennai                26

In [78]:
df.drop('Status',axis=1,inplace=True) #inplace =modifies the original data frame directly ,no need to reassign
df

  Name  Age     City country  Age_after_5years
0    a   23    Delhi   India                28
1    b   25   Mumbai   India                30
2    c   21  Chennai   India                26

# Vectorized Arthematic Operations in pandas

In [79]:
df=pd.DataFrame({
    'A':[10,20,30],
    'B':[1,2,3]
})
df

    A  B
0  10  1
1  20  2
2  30  3

In [80]:
df['A'+'B']=df['A']+df['B']
df

    A  B  AB
0  10  1  11
1  20  2  22
2  30  3  33

In [82]:
df['A-B']=df['A']-df['B']
df

    A  B  AB  A-B
0  10  1  11    9
1  20  2  22   18
2  30  3  33   27

In [83]:
df['A*B']=df['A']*df['B']
df

    A  B  AB  A-B  A*B
0  10  1  11    9   10
1  20  2  22   18   40
2  30  3  33   27   90

In [84]:
df['A/B']=df['A']/df['B']
df

    A  B  AB  A-B  A*B   A/B
0  10  1  11    9   10  10.0
1  20  2  22   18   40  10.0
2  30  3  33   27   90  10.0

In [85]:
df['A%B']=df['A']%df['B']
df

    A  B  AB  A-B  A*B   A/B  A%B
0  10  1  11    9   10  10.0    0
1  20  2  22   18   40  10.0    0
2  30  3  33   27   90  10.0    0

In [86]:
df['A**B']=df['A']**df['B']
df

    A  B  AB  A-B  A*B   A/B  A%B   A**B
0  10  1  11    9   10  10.0    0     10
1  20  2  22   18   40  10.0    0    400
2  30  3  33   27   90  10.0    0  27000

In [87]:
df['A+5']=df['A']+5
df['B*10']=df["B"]*10
df

    A  B  AB  A-B  A*B   A/B  A%B   A**B  A+5  B*10
0  10  1  11    9   10  10.0    0     10   15    10
1  20  2  22   18   40  10.0    0    400   25    20
2  30  3  33   27   90  10.0    0  27000   35    30

# Data Type Conversion

In [ ]:
#astype()---convert one data type to another