In [1]:
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
data={
    "Name":['A','B','C','D','E','F'],
    "Age":[25,30,35,40,45,50]
}
df=pd.DataFrame(data,index=[0,1,1,2,2,2])
df

  Name  Age
0    A   25
1    B   30
1    C   35
2    D   40
2    E   45
2    F   50

In [5]:
#reset_index
df_reset=df.reset_index(drop=True)
df_reset

  Name  Age
0    A   25
1    B   30
2    C   35
3    D   40
4    E   45
5    F   50

In [6]:
#drop duplacate index rows(keeps first occurrence)
df_unique=df[~df.index.duplicated(keep='first')]
df_unique

  Name  Age
0    A   25
1    B   30
2    D   40

In [7]:
#drop duplacate index rows(keeps last occurrence)
df_unique=df[~df.index.duplicated(keep='last')]
df_unique

  Name  Age
0    A   25
1    C   35
2    F   50

In [12]:
#drop all rows with duplacate (keeps none)
df_none=df[~df.index.duplicated(keep=False)]
df_none

  Name  Age
0    A   25

# selecting a cell /dataframe indexing

In [13]:
df=pd.DataFrame({
    'Name':['Ram','Sita','Ravi'],
    'Marks':[85,90,78],
    'City':['Delhi','Mumbai','Chennai']
},index=[101,102,103])
df

     Name  Marks     City
101   Ram     85    Delhi
102  Sita     90   Mumbai
103  Ravi     78  Chennai

In [17]:
#loc[row label,clo label
print(df.loc[102,"Marks"])
print(df.loc[103,'City'])

90
Chennai

In [20]:
#iloc[row index ,col index]
print(df.iloc[1,1])
print(df.iloc[0,2])
print(df.iloc[2,0])

90
Delhi
Ravi

In [21]:
#at [row laberl,column_label]
print(df.at[101,'Marks'])
print(df.at[102,'City'])

85
Mumbai

In [23]:
#iat[row_index,col_index]
print(df.iat[2,1])
print(df.iat[1,0])

78
Sita

In [24]:
#xs()-->cross section 
print(df.xs(102))

Name       Sita
Marks        90
City     Mumbai
Name: 102, dtype: object

In [25]:
df['Name']

101     Ram
102    Sita
103    Ravi
Name: Name, dtype: object

In [26]:
print(df[df['Marks']>80])

     Name  Marks    City
101   Ram     85   Delhi
102  Sita     90  Mumbai

In [27]:
df.loc[102:103]  #range not applied ,so give 2 records

     Name  Marks     City
102  Sita     90   Mumbai
103  Ravi     78  Chennai

In [28]:
df.iloc[1:2]

     Name  Marks    City
102  Sita     90  Mumbai

## groupby(), agg()

In [31]:
data={
    'EmpID':[1,2,3,4,5,6],
    'Name':['A','B','C','D','E','F'],
    'Department':['Sales','HR','Sales','IT','HR','IT'],
    'Salary':[50000,60000,50000,70000,60000,70000]
}
df=pd.DataFrame(data)
df

   EmpID Name Department  Salary
0      1    A      Sales   50000
1      2    B         HR   60000
2      3    C      Sales   50000
3      4    D         IT   70000
4      5    E         HR   60000
5      6    F         IT   70000

In [32]:
summary=df.groupby('Department').agg(
    avr_salary=("Salary","mean"),
    toatal_salary=("Salary","sum"),
    emp_count=("EmpID","count")
)
summary

            avr_salary  toatal_salary  emp_count
Department
HR             60000.0         120000          2
IT             70000.0         140000          2
Sales          50000.0         100000          2

In [33]:
#find max salary per department
max_salary=df.groupby("Department")["Salary"].max()
max_salary

Department
HR       60000
IT       70000
Sales    50000
Name: Salary, dtype: int64

In [34]:
#find min salary per department
min_salary=df.groupby("Department")["Salary"].min()
min_salary

Department
HR       60000
IT       70000
Sales    50000
Name: Salary, dtype: int64

In [35]:
mult=df.groupby("Department")["Salary"].agg(
    ['mean','sum','min','max','count','median']
)
mult

               mean     sum    min    max  count   median
Department
HR          60000.0  120000  60000  60000      2  60000.0
IT          70000.0  140000  70000  70000      2  70000.0
Sales       50000.0  100000  50000  50000      2  50000.0

In [36]:
a=df.groupby(['Department','Salary']).size()
a

Department  Salary
HR          60000     2
IT          70000     2
Sales       50000     2
dtype: int64

In [40]:
data={
    'OrderID':[1,2,3,4,5,6],
    'Region':['east','west','east','south','west','east'],
    'Product':['laptop','Moblie','laptop','tablet','laptop','mobile'],
    'Sales':[800,500,900,700,1200,400]  
}
df=pd.DataFrame(data)
byreg=df.groupby('Region')['Sales'].sum()
byreg

Region
east     2100
south     700
west     1700
Name: Sales, dtype: int64

In [41]:
avgprod=df.groupby('Product')['Sales'].mean()
avgprod

Product
Moblie    500.000000
laptop    966.666667
mobile    400.000000
tablet    700.000000
Name: Sales, dtype: float64

In [43]:
per=df.groupby('Region')['OrderID'].count()
per

Region
east     3
south    1
west     2
Name: OrderID, dtype: int64

# pivot table

In [44]:
data={
    'Region':['East','East','East','East','west','west','west','west','South','South','South','South'],
    'Product':['Laptop','Laptop','Moblie','Mobile','Laptop','Laptop','Tablet','Tablet','Moblie','Mobile','Tablet','Tablet'],
    'Sales':[800,500,600,400,1000,700,500,300,650,550,450,350],
    'Quantity':[5,3,4,2,6,4,3,2,5,3,4,2]
}
df=pd.DataFrame(data)
df

   Region Product  Sales  Quantity
0    East  Laptop    800         5
1    East  Laptop    500         3
2    East  Moblie    600         4
3    East  Mobile    400         2
4    west  Laptop   1000         6
5    west  Laptop    700         4
6    west  Tablet    500         3
7    west  Tablet    300         2
8   South  Moblie    650         5
9   South  Mobile    550         3
10  South  Tablet    450         4
11  South  Tablet    350         2