# pivot table

In [1]:
import pandas as pd
data={
    'Region':['East','East','East','East','west','west','west','west','South','South','South','South'],
    'Product':['Laptop','Laptop','Mobile','Mobile','Laptop','Laptop','Tablet','Tablet','Moblie','Mobile','Tablet','Tablet'],
    'Sales':[800,500,600,400,1000,700,500,300,650,550,450,350],
    'Quantity':[5,3,4,2,6,4,3,2,5,3,4,2]
}
df=pd.DataFrame(data)
df

   Region Product  Sales  Quantity
0    East  Laptop    800         5
1    East  Laptop    500         3
2    East  Mobile    600         4
3    East  Mobile    400         2
4    west  Laptop   1000         6
5    west  Laptop    700         4
6    west  Tablet    500         3
7    west  Tablet    300         2
8   South  Moblie    650         5
9   South  Mobile    550         3
10  South  Tablet    450         4
11  South  Tablet    350         2

In [2]:
pivot_index=pd.pivot_table(df, index ="Region",values='Sales',aggfunc='sum')
pivot_index

        Sales
Region
East     2300
South    2000
west     2500

In [3]:
pivot_column=pd.pivot_table(df,index="Region",columns='Product',values='Sales',aggfunc='sum')
pivot_column

Product  Laptop  Mobile  Moblie  Tablet
Region
East     1300.0  1000.0     NaN     NaN
South       NaN   550.0   650.0   800.0
west     1700.0     NaN     NaN   800.0

In [4]:
pivot_fill=pd.pivot_table(df,index="Region",columns='Product',values='Sales',aggfunc='sum',fill_value=0)

pivot_fill

Product  Laptop  Mobile  Moblie  Tablet
Region
East       1300    1000       0       0
South         0     550     650     800
west       1700       0       0     800

In [5]:
pivot_fill=pd.pivot_table(df,index="Region",columns='Product',values='Sales',aggfunc=['min','max'],fill_value=0)

pivot_fill

           min                         max
Product Laptop Mobile Moblie Tablet Laptop Mobile Moblie Tablet
Region
East       500    400      0      0    800    600      0      0
South        0    550    650    350      0    550    650    450
west       700      0      0    300   1000      0      0    500

In [6]:
pivot_column=pd.pivot_table(df,index="Region",columns='Product',values='Sales',aggfunc='count',fill_value=0)
pivot_column

Product  Laptop  Mobile  Moblie  Tablet
Region
East          2       2       0       0
South         0       1       1       2
west          2       0       0       2

In [7]:
pivot_sum=pd.pivot_table(df,index="Region",columns='Product',values='Sales',aggfunc='sum',fill_value=0,margins=True)
pivot_sum

Product  Laptop  Mobile  Moblie  Tablet   All
Region
East       1300    1000       0       0  2300
South         0     550     650     800  2000
west       1700       0       0     800  2500
All        3000    1550     650    1600  6800

## Crosstab

In [8]:
data ={
    'Employee':['jhon','james','david','mary','tom','charlie'],
    'Department':['Sales','HR','Sales','IT','HR','IT'],
    'Gender':['Male','Female','Male','Female','Male','Male'],
    'Salary':[50000,60000,50000,70000,62000,68000]
}
df=pd.DataFrame(data)
df

  Employee Department  Gender  Salary
0     jhon      Sales    Male   50000
1    james         HR  Female   60000
2    david      Sales    Male   50000
3     mary         IT  Female   70000
4      tom         HR    Male   62000
5  charlie         IT    Male   68000

In [9]:
#count of employes per department x genderc
ct=pd.crosstab(index=df['Department'],columns=df['Gender'])
ct

Gender      Female  Male
Department
HR               1     1
IT               1     1
Sales            0     2

In [10]:
ct_sum=pd.crosstab(index=df['Department'],columns=df['Gender'],values=df['Salary'],aggfunc='sum')
ct_sum

Gender       Female      Male
Department
HR          60000.0   62000.0
IT          70000.0   68000.0
Sales           NaN  100000.0

In [11]:
ct_mult=pd.crosstab(index=df['Department'],columns=df['Gender'],values=df['Salary'],aggfunc=['sum','mean'])
ct_mult

                sum               mean
Gender       Female      Male   Female     Male
Department
HR          60000.0   62000.0  60000.0  62000.0
IT          70000.0   68000.0  70000.0  68000.0
Sales           NaN  100000.0      NaN  50000.0

In [12]:
ct_mult=pd.crosstab(index=df['Department'],columns=df['Gender'],values=df['Salary'],aggfunc=['sum','mean'],margins=True)
ct_mult

                 sum                       mean
Gender        Female      Male     All   Female     Male      All
Department
HR           60000.0   62000.0  122000  60000.0  62000.0  61000.0
IT           70000.0   68000.0  138000  70000.0  68000.0  69000.0
Sales            NaN  100000.0  100000      NaN  50000.0  50000.0
All         130000.0  230000.0  360000  65000.0  57500.0  60000.0

In [13]:
ct_norm=pd.crosstab(index=df['Department'],columns=df['Gender'],normalize='index')
ct_norm

Gender      Female  Male
Department
HR             0.5   0.5
IT             0.5   0.5
Sales          0.0   1.0

## CONCATENATION

In [14]:
data_a={
    'EmpID':[1,2],
    'Name':['Jhon','Tom'],
    'Department':['Sales','HR']
}
data_b={
    "EmpID":[3,4],
    "Name":["David","Tom"],
    "Department":["IT","Sales"]
}
df_a=pd.DataFrame(data_a)
df_b=pd.DataFrame(data_b)
print(df_a)
print('-----------------')
print(df_b)

   EmpID  Name Department
0      1  Jhon      Sales
1      2   Tom         HR
-----------------
   EmpID   Name Department
0      3  David         IT
1      4    Tom      Sales

In [27]:
#row wise concatenation
row_con=pd.concat([df_a,df_b],axis=0,ignore_index=True)
row_con

   EmpID   Name Department
0      1   Jhon      Sales
1      2    Tom         HR
2      3  David         IT
3      4    Tom      Sales

In [28]:
#column wise concatenation
data_a={
    'EmpID':[1,2],
    'Name':['Jhon','Tom'],
}
data_b={
    "Department":["IT","Sales"],
    'salary':[50000,60000]
}
df_a=pd.DataFrame(data_a)
df_b=pd.DataFrame(data_b)
print(df_a)
print('-----------------')
print(df_b)

   EmpID  Name Department
0      1  Jhon      Sales
1      2   Tom         HR
-----------------
  Department  salary
0         IT   50000
1      Sales   60000

In [30]:
col_concat=pd.concat([df_a,df_b],axis=1)
col_concat

   EmpID  Name Department Department  salary
0      1  Jhon      Sales         IT   50000
1      2   Tom         HR      Sales   60000

# merging/joins

In [5]:
employees=pd.DataFrame({
    'EmpID':[1,2,3,4],
    'EmpName':['A','B','c','D'],
    'DeptID':[101,102,103,104]
})
departments=pd.DataFrame({
    'DeptID':[101,102,103,105],
    'DeptName':['HR','IT','Finance','Marketing']
})
print(employees)
print('-------------------------')
print(departments)

   EmpID EmpName  DeptID
0      1       A     101
1      2       B     102
2      3       c     103
3      4       D     104
-------------------------
   DeptID   DeptName
0     101         HR
1     102         IT
2     103    Finance
3     105  Marketing

In [8]:
# Inner join ----> it will returns common rows only
inner_join=pd.merge(employees,departments,on='DeptID',how='inner')
print(inner_join)

   EmpID EmpName  DeptID DeptName
0      1       A     101       HR
1      2       B     102       IT
2      3       c     103  Finance

In [39]:
# left join ----> all employees + matching depts
left_join=pd.merge(employees,departments,on='DeptID',how='left')
print(left_join)

   EmpID EmpName  DeptID DeptName
0      1       A     101       HR
1      2       B     102       IT
2      3       c     103  Finance
3      4       D     104      NaN

In [41]:
# Right join ----> all departments + matching emps
right_join=pd.merge(employees,departments,on='DeptID',how='right')
print(right_join)

   EmpID EmpName  DeptID   DeptName
0    1.0       A     101         HR
1    2.0       B     102         IT
2    3.0       c     103    Finance
3    NaN     NaN     105  Marketing

In [42]:
# outer join ----> all records from df's
outer_join=pd.merge(employees,departments,on='DeptID',how='outer')
print(outer_join)

   EmpID EmpName  DeptID   DeptName
0    1.0       A     101         HR
1    2.0       B     102         IT
2    3.0       c     103    Finance
3    4.0       D     104        NaN
4    NaN     NaN     105  Marketing